#pragma once

#include <SDL2/SDL.h>
#include <SDL2/SDL_vulkan.h>

typedef SDL_Keycode SprKey;

#define SPR_UNKNOWN               SDLK_UNKNOWN
#define SPR_RETURN                SDLK_RETURN
#define SPR_ESCAPE                SDLK_ESCAPE
#define SPR_BACKSPACE             SDLK_BACKSPACE
#define SPR_TAB                   SDLK_TAB
#define SPR_SPACE                 SDLK_SPACE
#define SPR_EXCLAIM               SDLK_EXCLAIM
#define SPR_QUOTEDBL              SDLK_QUOTEDBL
#define SPR_HASH                  SDLK_HASH
#define SPR_PERCENT               SDLK_PERCENT
#define SPR_DOLLAR                SDLK_DOLLAR
#define SPR_AMPERSAND             SDLK_AMPERSAND
#define SPR_QUOTE                 SDLK_QUOTE
#define SPR_LEFTPAREN             SDLK_LEFTPAREN
#define SPR_RIGHTPAREN            SDLK_RIGHTPAREN
#define SPR_ASTERISK              SDLK_ASTERISK
#define SPR_PLUS                  SDLK_PLUS
#define SPR_COMMA                 SDLK_COMMA
#define SPR_MINUS                 SDLK_MINUS
#define SPR_PERIOD                SDLK_PERIOD
#define SPR_SLASH                 SDLK_SLASH
#define SPR_0                     SDLK_0
#define SPR_1                     SDLK_1
#define SPR_2                     SDLK_2
#define SPR_3                     SDLK_3
#define SPR_4                     SDLK_4
#define SPR_5                     SDLK_5
#define SPR_6                     SDLK_6
#define SPR_7                     SDLK_7
#define SPR_8                     SDLK_8
#define SPR_9                     SDLK_9
#define SPR_COLON                 SDLK_COLON
#define SPR_SEMICOLON             SDLK_SEMICOLON
#define SPR_LESS                  SDLK_LESS
#define SPR_EQUALS                SDLK_EQUALS
#define SPR_GREATER               SDLK_GREATER
#define SPR_QUESTION              SDLK_QUESTION
#define SPR_AT                    SDLK_AT
#define SPR_LEFTBRACKET           SDLK_LEFTBRACKET
#define SPR_BACKSLASH             SDLK_BACKSLASH
#define SPR_RIGHTBRACKET          SDLK_RIGHTBRACKET
#define SPR_CARET                 SDLK_CARET
#define SPR_UNDERSCORE            SDLK_UNDERSCORE
#define SPR_BACKQUOTE             SDLK_BACKQUOTE
#define SPR_a                     SDLK_a
#define SPR_b                     SDLK_b
#define SPR_c                     SDLK_c
#define SPR_d                     SDLK_d
#define SPR_e                     SDLK_e
#define SPR_f                     SDLK_f
#define SPR_g                     SDLK_g
#define SPR_h                     SDLK_h
#define SPR_i                     SDLK_i
#define SPR_j                     SDLK_j
#define SPR_k                     SDLK_k
#define SPR_l                     SDLK_l
#define SPR_m                     SDLK_m
#define SPR_n                     SDLK_n
#define SPR_o                     SDLK_o
#define SPR_p                     SDLK_p
#define SPR_q                     SDLK_q
#define SPR_r                     SDLK_r
#define SPR_s                     SDLK_s
#define SPR_t                     SDLK_t
#define SPR_u                     SDLK_u
#define SPR_v                     SDLK_v
#define SPR_w                     SDLK_w
#define SPR_x                     SDLK_x
#define SPR_y                     SDLK_y
#define SPR_z                     SDLK_z
#define SPR_CAPSLOCK              SDLK_CAPSLOCK
#define SPR_F1                    SDLK_F1
#define SPR_F2                    SDLK_F2
#define SPR_F3                    SDLK_F3
#define SPR_F4                    SDLK_F4
#define SPR_F5                    SDLK_F5
#define SPR_F6                    SDLK_F6
#define SPR_F7                    SDLK_F7
#define SPR_F8                    SDLK_F8
#define SPR_F9                    SDLK_F9
#define SPR_F10                   SDLK_F10
#define SPR_F11                   SDLK_F11
#define SPR_F12                   SDLK_F12
#define SPR_PRINTSCREEN           SDLK_PRINTSCREEN
#define SPR_SCROLLLOCK            SDLK_SCROLLLOCK
#define SPR_PAUSE                 SDLK_PAUSE
#define SPR_INSERT                SDLK_INSERT
#define SPR_HOME                  SDLK_HOME
#define SPR_PAGEUP                SDLK_PAGEUP
#define SPR_DELETE                SDLK_DELETE
#define SPR_END                   SDLK_END
#define SPR_PAGEDOWN              SDLK_PAGEDOWN
#define SPR_RIGHT                 SDLK_RIGHT
#define SPR_LEFT                  SDLK_LEFT
#define SPR_DOWN                  SDLK_DOWN
#define SPR_UP                    SDLK_UP
#define SPR_NUMLOCKCLEAR          SDLK_NUMLOCKCLEAR
#define SPR_KP_DIVIDE             SDLK_KP_DIVIDE
#define SPR_KP_MULTIPLY           SDLK_KP_MULTIPLY
#define SPR_KP_MINUS              SDLK_KP_MINUS
#define SPR_KP_PLUS               SDLK_KP_PLUS
#define SPR_KP_ENTER              SDLK_KP_ENTER
#define SPR_KP_1                  SDLK_KP_1
#define SPR_KP_2                  SDLK_KP_2
#define SPR_KP_3                  SDLK_KP_3
#define SPR_KP_4                  SDLK_KP_4
#define SPR_KP_5                  SDLK_KP_5
#define SPR_KP_6                  SDLK_KP_6
#define SPR_KP_7                  SDLK_KP_7
#define SPR_KP_8                  SDLK_KP_8
#define SPR_KP_9                  SDLK_KP_9
#define SPR_KP_0                  SDLK_KP_0
#define SPR_KP_PERIOD             SDLK_KP_PERIOD
#define SPR_APPLICATION           SDLK_APPLICATION
#define SPR_POWER                 SDLK_POWER
#define SPR_KP_EQUALS             SDLK_KP_EQUALS
#define SPR_F13                   SDLK_F13
#define SPR_F14                   SDLK_F14
#define SPR_F15                   SDLK_F15
#define SPR_F16                   SDLK_F16
#define SPR_F17                   SDLK_F17
#define SPR_F18                   SDLK_F18
#define SPR_F19                   SDLK_F19
#define SPR_F20                   SDLK_F20
#define SPR_F21                   SDLK_F21
#define SPR_F22                   SDLK_F22
#define SPR_F23                   SDLK_F23
#define SPR_F24                   SDLK_F24
#define SPR_EXECUTE               SDLK_EXECUTE
#define SPR_HELP                  SDLK_HELP
#define SPR_MENU                  SDLK_MENU
#define SPR_SELECT                SDLK_SELECT
#define SPR_STOP                  SDLK_STOP
#define SPR_AGAIN                 SDLK_AGAIN
#define SPR_UNDO                  SDLK_UNDO
#define SPR_CUT                   SDLK_CUT
#define SPR_COPY                  SDLK_COPY
#define SPR_PASTE                 SDLK_PASTE
#define SPR_FIND                  SDLK_FIND
#define SPR_MUTE                  SDLK_MUTE
#define SPR_VOLUMEUP              SDLK_VOLUMEUP
#define SPR_VOLUMEDOWN            SDLK_VOLUMEDOWN
#define SPR_KP_COMMA              SDLK_KP_COMMA
#define SPR_KP_EQUALSAS400        SDLK_KP_EQUALSAS400
#define SPR_ALTERASE              SDLK_ALTERASE
#define SPR_SYSREQ                SDLK_SYSREQ
#define SPR_CANCEL                SDLK_CANCEL
#define SPR_CLEAR                 SDLK_CLEAR
#define SPR_PRIOR                 SDLK_PRIOR
#define SPR_RETURN2               SDLK_RETURN2
#define SPR_SEPARATOR             SDLK_SEPARATOR
#define SPR_OUT                   SDLK_OUT
#define SPR_OPER                  SDLK_OPER
#define SPR_CLEARAGAIN            SDLK_CLEARAGAIN
#define SPR_CRSEL                 SDLK_CRSEL
#define SPR_EXSEL                 SDLK_EXSEL
#define SPR_KP_00                 SDLK_KP_00
#define SPR_KP_000                SDLK_KP_000
#define SPR_THOUSANDSSEPARATOR    SDLK_THOUSANDSSEPARATOR
#define SPR_DECIMALSEPARATOR      SDLK_DECIMALSEPARATOR
#define SPR_CURRENCYUNIT          SDLK_CURRENCYUNIT
#define SPR_CURRENCYSUBUNIT       SDLK_CURRENCYSUBUNIT
#define SPR_KP_LEFTPAREN          SDLK_KP_LEFTPAREN
#define SPR_KP_RIGHTPAREN         SDLK_KP_RIGHTPAREN
#define SPR_KP_LEFTBRACE          SDLK_KP_LEFTBRACE
#define SPR_KP_RIGHTBRACE         SDLK_KP_RIGHTBRACE
#define SPR_KP_TAB                SDLK_KP_TAB
#define SPR_KP_BACKSPACE          SDLK_KP_BACKSPACE
#define SPR_KP_A                  SDLK_KP_A
#define SPR_KP_B                  SDLK_KP_B
#define SPR_KP_C                  SDLK_KP_C
#define SPR_KP_D                  SDLK_KP_D
#define SPR_KP_E                  SDLK_KP_E
#define SPR_KP_F                  SDLK_KP_F
#define SPR_KP_XOR                SDLK_KP_XOR
#define SPR_KP_POWER              SDLK_KP_POWER
#define SPR_KP_PERCENT            SDLK_KP_PERCENT
#define SPR_KP_LESS               SDLK_KP_LESS
#define SPR_KP_GREATER            SDLK_KP_GREATER
#define SPR_KP_AMPERSAND          SDLK_KP_AMPERSAND
#define SPR_KP_DBLAMPERSAND       SDLK_KP_DBLAMPERSAND
#define SPR_KP_VERTICALBAR        SDLK_KP_VERTICALBAR
#define SPR_KP_DBLVERTICALBAR     SDLK_KP_DBLVERTICALBAR
#define SPR_KP_COLON              SDLK_KP_COLON
#define SPR_KP_HASH               SDLK_KP_HASH
#define SPR_KP_SPACE              SDLK_KP_SPACE
#define SPR_KP_AT                 SDLK_KP_AT
#define SPR_KP_EXCLAM             SDLK_KP_EXCLAM
#define SPR_KP_MEMSTORE           SDLK_KP_MEMSTORE
#define SPR_KP_MEMRECALL          SDLK_KP_MEMRECALL
#define SPR_KP_MEMCLEAR           SDLK_KP_MEMCLEAR
#define SPR_KP_MEMADD             SDLK_KP_MEMADD
#define SPR_KP_MEMSUBTRACT        SDLK_KP_MEMSUBTRACT
#define SPR_KP_MEMMULTIPLY        SDLK_KP_MEMMULTIPLY
#define SPR_KP_MEMDIVIDE          SDLK_KP_MEMDIVIDE
#define SPR_KP_PLUSMINUS          SDLK_KP_PLUSMINUS
#define SPR_KP_CLEAR              SDLK_KP_CLEAR
#define SPR_KP_CLEARENTRY         SDLK_KP_CLEARENTRY
#define SPR_KP_BINARY             SDLK_KP_BINARY
#define SPR_KP_OCTAL              SDLK_KP_OCTAL
#define SPR_KP_DECIMAL            SDLK_KP_DECIMAL
#define SPR_KP_HEXADECIMAL        SDLK_KP_HEXADECIMAL
#define SPR_LCTRL                 SDLK_LCTRL
#define SPR_LSHIFT                SDLK_LSHIFT
#define SPR_LALT                  SDLK_LALT
#define SPR_LGUI                  SDLK_LGUI
#define SPR_RCTRL                 SDLK_RCTRL
#define SPR_RSHIFT                SDLK_RSHIFT
#define SPR_RALT                  SDLK_RALT
#define SPR_RGUI                  SDLK_RGUI
#define SPR_MODE                  SDLK_MODE
#define SPR_AUDIONEXT             SDLK_AUDIONEXT
#define SPR_AUDIOPREV             SDLK_AUDIOPREV
#define SPR_AUDIOSTOP             SDLK_AUDIOSTOP
#define SPR_AUDIOPLAY             SDLK_AUDIOPLAY
#define SPR_AUDIOMUTE             SDLK_AUDIOMUTE
#define SPR_MEDIASELECT           SDLK_MEDIASELECT
#define SPR_WWW                   SDLK_WWW
#define SPR_MAIL                  SDLK_MAIL
#define SPR_CALCULATOR            SDLK_CALCULATOR
#define SPR_COMPUTER              SDLK_COMPUTER
#define SPR_AC_SEARCH             SDLK_AC_SEARCH
#define SPR_AC_HOME               SDLK_AC_HOME
#define SPR_AC_BACK               SDLK_AC_BACK
#define SPR_AC_FORWARD            SDLK_AC_FORWARD
#define SPR_AC_STOP               SDLK_AC_STOP
#define SPR_AC_REFRESH            SDLK_AC_REFRESH
#define SPR_AC_BOOKMARKS          SDLK_AC_BOOKMARKS
#define SPR_BRIGHTNESSDOWN        SDLK_BRIGHTNESSDOWN
#define SPR_BRIGHTNESSUP          SDLK_BRIGHTNESSUP
#define SPR_DISPLAYSWITCH         SDLK_DISPLAYSWITCH
#define SPR_KBDILLUMTOGGLE        SDLK_KBDILLUMTOGGLE
#define SPR_KBDILLUMDOWN          SDLK_KBDILLUMDOWN
#define SPR_KBDILLUMUP            SDLK_KBDILLUMUP
#define SPR_EJECT                 SDLK_EJECT
#define SPR_SLEEP                 SDLK_SLEEP
#define SPR_APP1                  SDLK_APP1
#define SPR_APP2                  SDLK_APP2
#define SPR_AUDIOREWIND           SDLK_AUDIOREWIND
#define SPR_AUDIOFASTFORWARD      SDLK_AUDIOFASTFORWARD


namespace spr {
class KeyboardState {
public:
    void setKeyDown(SprKey key);
    void setKeyUp(SprKey key);

    bool isKeyDown(SprKey key);

    int timeSinceKeyDown[322];
    int timeSinceKeyUp[322];
private:
    bool keyDown[322];
};
}